_format_version: "3.0"

services:
  - name: banking-api
    url: http://api-service:5000
    
routes:
  # Existing routes
  - name: health
    service: banking-api
    paths: ["/health"]
    methods: ["GET"]
    
  - name: teams
    service: banking-api
    paths: ["/api/v1/teams"]
    methods: ["GET"]
    
  - name: legacy
    service: banking-api
    paths: ["/api/v1/legacy"]
    methods: ["POST"]
    
  - name: bulk-extract
    service: banking-api
    paths: ["/api/v1/bulk/extract"]
    methods: ["POST"]
    
  # CSV processing routes
  - name: csv-upload
    service: banking-api
    paths: ["/api/v1/csv/upload"]
    methods: ["POST"]
    
  - name: csv-download
    service: banking-api
    paths: ["/api/v1/csv/download"]
    methods: ["GET"]
    
  - name: csv-data-api
    service: banking-api
    paths: ["/api/v1/csv/data"]
    methods: ["GET"]
    
  # NEW: Audit logs
  - name: audit-logs
    service: banking-api
    paths: ["/api/v1/audit/logs"]
    methods: ["GET"]
    
  - name: root
    service: banking-api
    paths: ["/"]
    methods: ["GET"]

plugins:
  - name: cors
    config:
      origins: ["*"]
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      headers: ["Accept", "Content-Type", "X-Team", "Authorization"]
      
  - name: rate-limiting
    config:
      minute: 1000
      hour: 10000